version: '3.9'

services:
  # Postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./posgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=vietjet


  #Redis
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
